config/routes.rb
DavinciMotors::Application.routes.draw do
  root :to => "cars#index"
  resources :users, only: [:new, :create]
  resources :cars do
    member do
      #get '/cars/:id/claim', to: 'cars#claim'
      get 'claim', as: 'claim'
      get 'unclaim', as: 'unclaim'
    end

    # collection do
    # ...
    # end
  end

  get 'my_cars', to: 'cars#my_cars'

  get 'login',
    to: 'sessions#login', #goes here b/c going to use sessions controllers
    as: 'login'

  post 'login',
    to: 'sessions#create' #This is a pretty bare branch, but it uses same login path
  # as get 'login', so we borrow from that.

  delete 'logout',
    to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth'
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, :model, :year, presence: true
  validates :price, presence: true, numericality: {
      :greater_than_or_equal_to => 0.01, :less_than => 1_000_000  }

  belongs_to :user
end

app/models/student.rb
class Student < ActiveRecord::Base

  scope :males, -> { where(sex: 'M') }
  scope :females, -> { where(sex: 'F')}
  scope :teenagers, -> { where(date_of_birth: (20.years.ago)..(13.years.ago)).order(
      date_of_birth: :desc)}
  scope :tweens, -> { where(date_of_birth: (13.years.ago)..(10.years.ago)).order(
      date_of_birth: :desc)}

  1) Student.where(eye_color: 'blue').count

  scope :height, -> {where(height: 101...200).count}

  3) Student.order(:height).last

  4) Student.order(:height).limit(10)

  5) Student.where(:date_of_birth => [\d{4}-04-\d{2}])

  6)Student.where(eye_color: 'green', hair_color: 'brown').count




  def self.seed_data!
    ages = (5..18).to_a
    heights = {
        5  => (40..46).to_a,
        6  => (42..49).to_a,
        7  => (44..52).to_a,
        8  => (47..54).to_a,
        9  => (49..57).to_a,
        10 => (50..59).to_a,
        11 => (52..61).to_a,
        12 => (54..64).to_a,
        13 => (56..66).to_a,
        14 => (59..70).to_a,
        15 => (62..72).to_a,
        16 => (63..73).to_a,
        17 => (64..74).to_a,
        18 => (65..75).to_a,
    }
    500.times do |number|
      age = ages.sample
      date_of_birth = (age).years.ago + rand(11).months + rand(30).days
      height = heights[age].sample
      Student.create(
          :first_name => Faker::Name.first_name,
          :middle_name => Faker::Name.first_name,
          :last_name => Faker::Name.last_name,
          :date_of_birth => date_of_birth,
          :hair_color => ['red', 'brown', 'black', 'blonde'].sample,
          :eye_color => ['blue', 'green', 'brown'].sample,
          :height => height,
          :weight => random_weight_for_height(height),
          :sex => ['M', 'F'].sample
      )
    end
  end

  private

  def self.random_weight_for_height(height)
    bmi = (19..40).to_a.sample
    sprintf("%.2f", ((height * height) * bmi)/703)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #class method that validates password & encrypts. no way to get back original digits
  has_secure_password(validations: false) #sets it to not do the validations

  validates_confirmation_of :password, # matching
    if: lambda { |user| !user.omniauth? && user.password.present? }
  validates_presence_of :password, :on => :create, # existence
    if: lambda { |user| !user.omniauth? }
  validates_presence_of :password_confirmation, # existence
    if: lambda { |user| !user.omniauth? && user.password.present? }

  has_many :cars

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user #says "this method in controller is also a helper in views"

  private
  #stores the session information from cookies in the server,
  # a link to that session is stored on the browser
  #session is a hash, :user_id is the key
  def current_user
  #memoization
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :claim, :unclaim]

  def index
    @cars = Car.where(user_id: nil)
  end

  def my_cars
    @cars = Car.where(user: current_user)
    render action: 'index'
  end

  def show

  end

  def new
    @car = Car.new
  end

  def edit

  end

  def claim
    @car.user = current_user
    if @car.save
      redirect_to root_path, notice:
      "#{@car.make} #{@car.model} has been moved to your inventory"
    else
      redirect_to root_path, error: 'Unable to claim car.'
    end
  end

  def unclaim
    @car.user_id = nil
    if @car.save
      redirect_to my_cars_path, notice:
      "#{@car.make} #{@car.model} has been moved out of your inventory"
    else
      redirect_to my_cars_path, error: "Can't unclaim car."
    end
  end

  def create
    @car = Car.new(car_params)
    #redirect_to cars_path, notice: "#{@car.year} #{@car.make} #{@car.model} created"
    if @car.save
       redirect_to root_path, notice: "#{@car.year} #{@car.make} #{@car.model} created"
    else
      render action: 'new'
    end
  end

  def update
      if @car.update(car_params)
        redirect_to root_path, notice: 'Car was successfully updated.'
      else
        render action: 'edit'
      end
    end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:make, :model, :year, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def oauth
    @user = User.where(
        email: omniauth_options[:email]
        ).first_or_initialize(omniauth_options)
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome back #{@user.first_name}"
    else
      render 'users/new'
    end
  end

  def create
    #old way: User.find_by_email(params[:email])
    user = User.where(email: params[:email]).first
    #where method returns ActiveRecord::Relation so you can chain them
    if user && user.authenticate(params[:password])
      # User has correct password
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back #{user.first_name}"
    else
      # User does not exist, or has invalid password
      flash[:alert] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    if user = current_user
    session.delete(:user_id)
    redirect_to root_path, notice: "#{user.email} has been logged out"
    end
  end

  private
  def omniauth_options
    if auth_hash = request.env['omniauth.auth']
      first_name, last_name = auth_hash[:info][:name].split(/\s+/, 2)
      {
          email: auth_hash[:info][:email],
          first_name: first_name,
          last_name: last_name,
          omniauth: true
      }
    end
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  def new
    @user = User.new #because model is user.rb
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id #method to look up id, then stores it in session hash
      redirect_to root_path, notice: "Thank you for signing up #{@user.first_name}"
    else
      render 'new' #action:
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation, :omniauth)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :make, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :make, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:make) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr id="<%= dom_id(car) %>">
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= number_to_currency(car.price) %></td>

        <td>
          <% if current_user.present? %>
          <!--if params[:action] == "my_cars" %>-->
              <% if car.user == current_user %>
                  <%= link_to t('.unclaim', :default => t("helpers.links.unclaim")),
                              unclaim_car_path(car), :class => 'btn btn-mini btn-warning' %>
              <% else %>
                  <%= link_to t('.claim', :default => t("helpers.links.claim")),
                              claim_car_path(car), :class => 'btn btn-mini btn-success' %>
              <% end %>
          <% end %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_car_path(car), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          car_path(car),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new"),
            :model => model_class.model_name.human.titleize),
            new_car_path,
            :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:make) %>:</strong></dt>
  <dd><%= @car.make %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @car.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @car.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @car.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @car.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_authentication.html.erb
<% if current_user.present? %>
    <% navigation_dropdown_text = "Signed in as #{current_user.email}" %>
<% else %>
    <% navigation_dropdown_text = "Signup / Login" %>
<% end %>

<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= navigation_dropdown_text %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <% if current_user.present? %>
          <li class="divider"></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Signup', new_user_path %></li>
          <li><%= link_to 'Login', login_path %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'DaVinci Motors', root_path, class: 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "My Cars", my_cars_path %></li>
          <li><%= link_to "Nav Link 2" %></li>
          <li><%= link_to "Nav Link 3" %></li>
        </ul>
        <%= render partial: "layouts/authentication" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
    <div class='flash' id='<% type %>'>
      <%= message %>
    </div>
<% end %>

<div class="container">
    <%= render partial: 'layouts/navigation' %>
    <%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.class.name %> from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <% if @user.omniauth? %>
        <%= f.hidden_field :omniauth %>
    <% else %>
        <div class="field">
          <%= f.label :password %><br>
          <%= f.text_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.text_field :password_confirmation %>
        </div>
    <% end %>
    <div class="actions">
      <%= f.submit 'Signup'%>
    </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% unless @user.omniauth? %>
    <div>
      <%= image_tag('octocat.png', size: '200x200' ) %>
      <%= link_to button_tag('Sign up via Github'), '/auth/github' %>
    </div>
    <div>
      <h1>Signup</h1>
    </div>
<% else %>
    <h1>Verify Details</h1>
<% end %>

<%= render 'users/form' %>
<%= link_to 'Back', users_path %>